# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

# development:
#   secret_key_base: 105a884f29f8f5cc34bd28d9997401034d94080260796b1ce0942a2e17622c7d9f60a1d651a9f51992b5defc855576eecbd8d89c5f73a41d7c43c38075d44b11
#
# test:
#   secret_key_base: 31207b12aca5fdd2fd1c4332add94461ff2ed1ecbdbf4fef41cd2cf20be8b87046eb5f12e8689a19749352371f62b054a85a33819d74f652007b456d096fa200
#
# # Do not keep production secrets in the unencrypted secrets file.
# # Instead, either read values from the environment.
# # Or, use `bin/rails secrets:setup` to configure encrypted secrets
# # and move the `production:` environment over there.
#
# production:
#   secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  secret_key_base: 105a884f29f8f5cc34bd28d9997401034d94080260796b1ce0942a2e17622c7d9f60a1d651a9f51992b5defc855576eecbd8d89c5f73a41d7c43c38075d44b11
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>
test:
  secret_key_base: 31207b12aca5fdd2fd1c4332add94461ff2ed1ecbdbf4fef41cd2cf20be8b87046eb5f12e8689a19749352371f62b054a85a33819d74f652007b456d096fa200
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>
